import { Injectable } from '@angular/core';
import { User } from '../models/user.interface';
import { Site } from '../models/site.interface';
import { Sector } from '../models/sector.interface';
import { Patient } from '../models/patient.interface';
import { Exam } from '../models/exam.interface';
import { Conversation, Message } from '../models/conversation.interface';

@Injectable({
  providedIn: 'root'
})
export class MockDataService {
  private generateId(): string {
    return Math.random().toString(36).substr(2, 9);
  }

  generateUsers(): User[] {
    return [
      { id: 'U001', firstName: 'Damien', lastName: 'Petit', email: 'damien.petit@chu-angers.fr', specialty: 'Oncologist', site: 'CHU-Angers', isActive: true },
      { id: 'U002', firstName: 'Nicolas', lastName: 'Martin', email: 'nicolas.martin@chu-caen.fr', specialty: 'Oncologist', site: 'CHU-Caen', isActive: true },
      { id: 'U003', firstName: 'Déborah', lastName: 'Dupont', email: 'deborah.dupont@chu-angers.fr', specialty: 'Pediatrician', site: 'CHU-Angers', isActive: true },
      { id: 'U004', firstName: 'Daniel', lastName: 'Bernard', email: 'daniel.bernard@chu-caen.fr', specialty: 'Radiographer', site: 'CHU-Caen', isActive: true },
      { id: 'U005', firstName: 'Sylvie', lastName: 'Moreau', email: 'sylvie.moreau@chu-caen.fr', specialty: 'General Practitioner', site: 'CHU-Caen', isActive: true },
      { id: 'U006', firstName: 'Claire', lastName: 'Rousseau', email: 'claire.rousseau@chu-brest.fr', specialty: 'Cardiologist', site: 'CHU-Brest', isActive: true },
      { id: 'U007', firstName: 'Julien', lastName: 'Leroy', email: 'julien.leroy@chu-brest.fr', specialty: 'Emergency Physician', site: 'CHU-Brest', isActive: true },
      { id: 'U008', firstName: 'Fatima', lastName: 'Benali', email: 'fatima.benali@chu-brest.fr', specialty: 'Neurologist', site: 'CHU-Brest', isActive: true },
      { id: 'U009', firstName: 'Thomas', lastName: 'Dubois', email: 'thomas.dubois@chu-angers.fr', specialty: 'Orthopedic Surgeon', site: 'CHU-Angers', isActive: true },
      { id: 'U010', firstName: 'Marie', lastName: 'Roux', email: 'marie.roux@remote-site.fr', specialty: 'Head Nurse', site: 'Remote site', isActive: true }
    ];
  }

  generateSites(): Site[] {
    return [
      { id: 'S001', name: 'CHU-Angers', type: 'public', address: '4 rue Larrey', city: 'Angers', phone: '02 41 35 36 37', isActive: true },
      { id: 'S002', name: 'CHU-Caen', type: 'public', address: 'Avenue de la Côte de Nacre', city: 'Caen', phone: '02 31 06 31 06', isActive: true },
      { id: 'S003', name: 'CHU-Brest', type: 'public', address: 'Boulevard Tanguy Prigent', city: 'Brest', phone: '02 98 34 71 85', isActive: true },
      { id: 'S004', name: 'Remote site', type: 'private', address: '15 rue de la Télémédecine', city: 'Tours', phone: '02 47 75 45 45', isActive: true },
      { id: 'S005', name: 'CH Le Mans', type: 'public', address: '194 avenue Rubillard', city: 'Le Mans', phone: '02 43 43 43 43', isActive: true },
      { id: 'S006', name: 'AZ Sint-Maarten', type: 'private', address: 'Rooienberg 25', city: 'Duffel', phone: '+32 15 30 50 11', isActive: true }
    ];
  }

  generateSectors(): Sector[] {
    return [
      { id: 'SEC001', name: 'Colon', siteId: 'S001', siteName: 'CHU-Angers', description: 'Colorectal surgery and treatment', isActive: true },
      { id: 'SEC002', name: 'Cytology', siteId: 'S001', siteName: 'CHU-Angers', description: 'Cell structure analysis', isActive: true },
      { id: 'SEC003', name: 'Fluorescence', siteId: 'S001', siteName: 'CHU-Angers', description: 'Fluorescence imaging', isActive: true },
      { id: 'SEC004', name: 'Lungs', siteId: 'S003', siteName: 'CHU-Brest', description: 'Pulmonary medicine', isActive: true },
      { id: 'SEC005', name: 'Chest', siteId: 'S003', siteName: 'CHU-Brest', description: 'Thoracic medicine', isActive: true },
      { id: 'SEC006', name: 'Breast', siteId: 'S003', siteName: 'CHU-Brest', description: 'Breast cancer screening', isActive: true },
      { id: 'SEC007', name: 'Histology', siteId: 'S003', siteName: 'CHU-Brest', description: 'Tissue analysis', isActive: true },
      { id: 'SEC008', name: 'Throat', siteId: 'S002', siteName: 'CHU-Caen', description: 'ENT specialty', isActive: true },
      { id: 'SEC009', name: 'Oncology', siteId: 'S002', siteName: 'CHU-Caen', description: 'Cancer treatment', isActive: true },
      { id: 'SEC010', name: 'General', siteId: 'S002', siteName: 'CHU-Caen', description: 'General medicine', isActive: true }
    ];
  }

  generatePatients(): Patient[] {
    return [
      { id: 'P001', firstName: 'Adam', lastName: 'Morel', dateOfBirth: new Date('2005-03-14'), gender: 'M', bloodType: 'O+', phone: '0624583912', email: 'adam.morel@example.com', address: '12 rue des Acacias, 57000 Metz', socialSecurityNumber: '105031445812345', createdAt: new Date('2023-01-15') },
      { id: 'P002', firstName: 'Gabriel', lastName: 'Laurent', dateOfBirth: new Date('1998-07-02'), gender: 'M', bloodType: 'A-', phone: '0645728109', email: 'gabriel.laurent@example.com', address: '45 avenue de la Liberté, 54000 Nancy', socialSecurityNumber: '198072245709876', createdAt: new Date('2023-02-20') },
      { id: 'P003', firstName: 'Rebecca', lastName: 'Cohen', dateOfBirth: new Date('1985-11-21'), gender: 'F', bloodType: 'B+', phone: '0758669310', email: 'rebecca.cohen@example.com', address: '7 place Saint-Jacques, 75004 Paris', socialSecurityNumber: '285112145896732', createdAt: new Date('2023-03-10') },
      { id: 'P004', firstName: 'Emmy', lastName: 'Dubois', dateOfBirth: new Date('2010-06-05'), gender: 'F', bloodType: 'AB-', phone: '0687142954', email: 'emmy.dubois@example.com', address: '18 rue des Lilas, 69003 Lyon', socialSecurityNumber: '210060545879611', createdAt: new Date('2023-04-05') },
      { id: 'P005', firstName: 'Bastien', lastName: 'Leroy', dateOfBirth: new Date('1992-09-17'), gender: 'M', bloodType: 'O-', phone: '0722483177', email: 'bastien.leroy@example.com', address: '30 rue de Verdun, 31000 Toulouse', socialSecurityNumber: '192091745123498', createdAt: new Date('2023-05-12') },
      { id: 'P006', firstName: 'Lucie', lastName: 'Bernard', dateOfBirth: new Date('2001-01-29'), gender: 'F', bloodType: 'A+', phone: '0639275502', email: 'lucie.bernard@example.com', address: '4 rue Victor Hugo, 13001 Marseille', socialSecurityNumber: '201012945876564', createdAt: new Date('2023-06-18') },
      { id: 'P007', firstName: 'Sophie', lastName: 'Girard', dateOfBirth: new Date('1978-12-03'), gender: 'F', bloodType: 'B-', phone: '0756891234', email: 'sophie.girard@example.com', address: '22 boulevard Haussmann, 75009 Paris', socialSecurityNumber: '278120345612789', createdAt: new Date('2023-07-22') },
      { id: 'P008', firstName: 'Marc', lastName: 'Lefebvre', dateOfBirth: new Date('1965-08-15'), gender: 'M', bloodType: 'AB+', phone: '0634567890', email: 'marc.lefebvre@example.com', address: '8 rue de la Paix, 44000 Nantes', socialSecurityNumber: '165081534567123', createdAt: new Date('2023-08-10') },
      { id: 'P009', firstName: 'Claire', lastName: 'Fontaine', dateOfBirth: new Date('1990-04-22'), gender: 'F', bloodType: 'O+', phone: '0698765432', email: 'claire.fontaine@example.com', address: '15 avenue des Champs, 67000 Strasbourg', socialSecurityNumber: '190042234567890', createdAt: new Date('2023-09-05') },
      { id: 'P010', firstName: 'Antoine', lastName: 'Roussel', dateOfBirth: new Date('1982-11-08'), gender: 'M', bloodType: 'A+', phone: '0612345678', email: 'antoine.roussel@example.com', address: '33 rue Nationale, 59000 Lille', socialSecurityNumber: '182110834567234', createdAt: new Date('2023-10-12') }
    ];
  }

  generateExams(): Exam[] {
    return [
      // Adam Morel - P001 (3 exams)
      {
        id: 'E001-01',
        patientId: 'P001',
        patientName: 'Adam Morel',
        patientBirthDate: new Date('2005-03-14'),
        patientGender: 'M',
        title: 'CT Scan - Thorax',
        anatomicalRegion: 'Thorax',
        examDate: new Date('2025-01-15'),
        patientWeight: 65,
        patientAge: 19,
        diagnosis: 'negative',
        department: 'Radiology',
        description: 'Thoracic CT scan for follow-up due to persistent pain.',
        conclusion: 'Normal examination, no abnormalities detected.',
        prescribingPhysician: 'Dr. Jean Dupont',
        assignedRadiologist: 'Damien Petit',
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC001',
        sectorName: 'Colon',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E001-02',
        patientId: 'P001',
        patientName: 'Adam Morel',
        patientBirthDate: new Date('2005-03-14'),
        patientGender: 'M',
        title: 'MRI - Knee',
        anatomicalRegion: 'Lower limbs',
        examDate: new Date('2025-01-10'),
        patientWeight: 65,
        patientAge: 19,
        diagnosis: 'pending',
        department: 'Orthopedics',
        description: 'Knee MRI following sports trauma.',
        conclusion: 'Analysis in progress, results pending validation.',
        prescribingPhysician: 'Dr. Marie Leclerc',
        assignedRadiologist: null,
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC010',
        sectorName: 'General',
        status: 'in-progress',
        isUrgent: true
      },
      {
        id: 'E001-03',
        patientId: 'P001',
        patientName: 'Adam Morel',
        patientBirthDate: new Date('2005-03-14'),
        patientGender: 'M',
        title: 'X-Ray - Shoulder',
        anatomicalRegion: 'Shoulder',
        examDate: new Date('2024-12-20'),
        patientWeight: 64,
        patientAge: 19,
        diagnosis: 'negative',
        department: 'Emergency',
        description: 'Shoulder X-ray after fall.',
        conclusion: 'No visible fracture, mild contusion.',
        prescribingPhysician: 'Dr. Pierre Martin',
        assignedRadiologist: 'Nicolas Martin',
        siteId: 'S002',
        siteName: 'CHU-Caen',
        sectorId: 'SEC010',
        sectorName: 'General',
        status: 'completed',
        isUrgent: false
      },

      // Gabriel Laurent - P002 (4 exams including cytology)
      {
        id: 'E002-01',
        patientId: 'P002',
        patientName: 'Gabriel Laurent',
        patientBirthDate: new Date('1998-07-02'),
        patientGender: 'M',
        title: 'Cytology - Bronchi',
        anatomicalRegion: 'Thorax',
        examDate: new Date('2025-01-14'),
        patientWeight: 75,
        patientAge: 26,
        diagnosis: 'positive',
        department: 'Pulmonology',
        description: 'Cytological analysis of bronchial secretions.',
        conclusion: 'Atypical cells detected, additional investigations required.',
        prescribingPhysician: 'Dr. Sophie Durand',
        assignedRadiologist: 'Déborah Dupont',
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC002',
        sectorName: 'Cytology',
        status: 'completed',
        isUrgent: true
      },
      {
        id: 'E002-02',
        patientId: 'P002',
        patientName: 'Gabriel Laurent',
        patientBirthDate: new Date('1998-07-02'),
        patientGender: 'M',
        title: 'CT Scan - Thorax',
        anatomicalRegion: 'Thorax',
        examDate: new Date('2025-01-12'),
        patientWeight: 75,
        patientAge: 26,
        diagnosis: 'pending',
        department: 'Radiology',
        description: 'Thoracic CT scan for pulmonary investigation.',
        conclusion: 'Analysis in progress, results pending validation.',
        prescribingPhysician: 'Dr. Michel Bernard',
        assignedRadiologist: null,
        siteId: 'S003',
        siteName: 'CHU-Brest',
        sectorId: 'SEC004',
        sectorName: 'Lungs',
        status: 'scheduled',
        isUrgent: false
      },
      {
        id: 'E002-03',
        patientId: 'P002',
        patientName: 'Gabriel Laurent',
        patientBirthDate: new Date('1998-07-02'),
        patientGender: 'M',
        title: 'Biopsy - Lung',
        anatomicalRegion: 'Thorax',
        examDate: new Date('2025-01-08'),
        patientWeight: 75,
        patientAge: 26,
        diagnosis: 'positive',
        department: 'Pulmonology',
        description: 'CT-guided lung biopsy.',
        conclusion: 'Malignant lesion confirmed, oncological treatment recommended.',
        prescribingPhysician: 'Dr. Anne Rousseau',
        assignedRadiologist: 'Claire Rousseau',
        siteId: 'S003',
        siteName: 'CHU-Brest',
        sectorId: 'SEC007',
        sectorName: 'Histology',
        status: 'completed',
        isUrgent: true
      },
      {
        id: 'E002-04',
        patientId: 'P002',
        patientName: 'Gabriel Laurent',
        patientBirthDate: new Date('1998-07-02'),
        patientGender: 'M',
        title: 'PET Scan - Whole body',
        anatomicalRegion: 'Whole body',
        examDate: new Date('2024-12-15'),
        patientWeight: 74,
        patientAge: 26,
        diagnosis: 'negative',
        department: 'Nuclear medicine',
        description: 'PET scan for oncological staging.',
        conclusion: 'No pathological uptake detected.',
        prescribingPhysician: 'Dr. François Moreau',
        assignedRadiologist: 'Fatima Benali',
        siteId: 'S002',
        siteName: 'CHU-Caen',
        sectorId: 'SEC009',
        sectorName: 'Oncology',
        status: 'completed',
        isUrgent: false
      },

      // Rebecca Cohen - P003 (5 exams including cytology)
      {
        id: 'E003-01',
        patientId: 'P003',
        patientName: 'Rebecca Cohen',
        patientBirthDate: new Date('1985-11-21'),
        patientGender: 'F',
        title: 'Cytology - Cervical smear',
        anatomicalRegion: 'Pelvis',
        examDate: new Date('2025-01-13'),
        patientWeight: 62,
        patientAge: 39,
        diagnosis: 'negative',
        department: 'Gynecology',
        description: 'Cervical screening smear.',
        conclusion: 'Normal cells, no abnormalities detected.',
        prescribingPhysician: 'Dr. Catherine Petit',
        assignedRadiologist: 'Déborah Dupont',
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC002',
        sectorName: 'Cytology',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E003-02',
        patientId: 'P003',
        patientName: 'Rebecca Cohen',
        patientBirthDate: new Date('1985-11-21'),
        patientGender: 'F',
        title: 'Mammography - Breast',
        anatomicalRegion: 'Thorax',
        examDate: new Date('2025-01-11'),
        patientWeight: 62,
        patientAge: 39,
        diagnosis: 'pending',
        department: 'Radiology',
        description: 'Annual screening mammography.',
        conclusion: 'Analysis in progress, results pending validation.',
        prescribingPhysician: 'Dr. Jean Dupont',
        assignedRadiologist: null,
        siteId: 'S003',
        siteName: 'CHU-Brest',
        sectorId: 'SEC006',
        sectorName: 'Breast',
        status: 'in-progress',
        isUrgent: false
      },
      {
        id: 'E003-03',
        patientId: 'P003',
        patientName: 'Rebecca Cohen',
        patientBirthDate: new Date('1985-11-21'),
        patientGender: 'F',
        title: 'Ultrasound - Abdomen',
        anatomicalRegion: 'Abdomen',
        examDate: new Date('2025-01-05'),
        patientWeight: 62,
        patientAge: 39,
        diagnosis: 'negative',
        department: 'Internal medicine',
        description: 'Abdominal ultrasound for persistent pain.',
        conclusion: 'Normal abdominal organs.',
        prescribingPhysician: 'Dr. Marie Leclerc',
        assignedRadiologist: 'Thomas Dubois',
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC010',
        sectorName: 'General',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E003-04',
        patientId: 'P003',
        patientName: 'Rebecca Cohen',
        patientBirthDate: new Date('1985-11-21'),
        patientGender: 'F',
        title: 'MRI - Pelvis',
        anatomicalRegion: 'Pelvis',
        examDate: new Date('2024-12-28'),
        patientWeight: 61,
        patientAge: 39,
        diagnosis: 'negative',
        department: 'Gynecology',
        description: 'Pelvic MRI for gynecological assessment.',
        conclusion: 'Normal pelvic structures.',
        prescribingPhysician: 'Dr. Pierre Martin',
        assignedRadiologist: 'Julien Leroy',
        siteId: 'S002',
        siteName: 'CHU-Caen',
        sectorId: 'SEC010',
        sectorName: 'General',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E003-05',
        patientId: 'P003',
        patientName: 'Rebecca Cohen',
        patientBirthDate: new Date('1985-11-21'),
        patientGender: 'F',
        title: 'Cytology - Pleural fluid',
        anatomicalRegion: 'Thorax',
        examDate: new Date('2024-11-15'),
        patientWeight: 61,
        patientAge: 39,
        diagnosis: 'negative',
        department: 'Pulmonology',
        description: 'Cytological analysis of pleural fluid.',
        conclusion: 'No malignant cells detected.',
        prescribingPhysician: 'Dr. Sophie Durand',
        assignedRadiologist: 'Déborah Dupont',
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC002',
        sectorName: 'Cytology',
        status: 'completed',
        isUrgent: false
      },

      // Emmy Dubois - P004 (2 exams)
      {
        id: 'E004-01',
        patientId: 'P004',
        patientName: 'Emmy Dubois',
        patientBirthDate: new Date('2010-06-05'),
        patientGender: 'F',
        title: 'X-Ray - Skull',
        anatomicalRegion: 'Head',
        examDate: new Date('2025-01-09'),
        patientWeight: 45,
        patientAge: 14,
        diagnosis: 'negative',
        department: 'Pediatrics',
        description: 'Skull X-ray after fall.',
        conclusion: 'No visible fracture.',
        prescribingPhysician: 'Dr. Michel Bernard',
        assignedRadiologist: 'Déborah Dupont',
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC010',
        sectorName: 'General',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E004-02',
        patientId: 'P004',
        patientName: 'Emmy Dubois',
        patientBirthDate: new Date('2010-06-05'),
        patientGender: 'F',
        title: 'Ultrasound - Abdomen',
        anatomicalRegion: 'Abdomen',
        examDate: new Date('2024-12-22'),
        patientWeight: 44,
        patientAge: 14,
        diagnosis: 'negative',
        department: 'Pediatrics',
        description: 'Abdominal ultrasound for pain.',
        conclusion: 'Normal abdominal organs for age.',
        prescribingPhysician: 'Dr. Anne Rousseau',
        assignedRadiologist: 'Déborah Dupont',
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC010',
        sectorName: 'General',
        status: 'completed',
        isUrgent: false
      },

      // Bastien Leroy - P005 (3 exams)
      {
        id: 'E005-01',
        patientId: 'P005',
        patientName: 'Bastien Leroy',
        patientBirthDate: new Date('1992-09-17'),
        patientGender: 'M',
        title: 'CT Scan - Abdomen',
        anatomicalRegion: 'Abdomen',
        examDate: new Date('2025-01-07'),
        patientWeight: 78,
        patientAge: 32,
        diagnosis: 'pending',
        department: 'Surgery',
        description: 'Pre-operative abdominal CT scan.',
        conclusion: 'Analysis in progress, results pending validation.',
        prescribingPhysician: 'Dr. François Moreau',
        assignedRadiologist: null,
        siteId: 'S002',
        siteName: 'CHU-Caen',
        sectorId: 'SEC010',
        sectorName: 'General',
        status: 'scheduled',
        isUrgent: false
      },
      {
        id: 'E005-02',
        patientId: 'P005',
        patientName: 'Bastien Leroy',
        patientBirthDate: new Date('1992-09-17'),
        patientGender: 'M',
        title: 'MRI - Spine',
        anatomicalRegion: 'Back',
        examDate: new Date('2024-12-30'),
        patientWeight: 78,
        patientAge: 32,
        diagnosis: 'positive',
        department: 'Neurology',
        description: 'Spinal MRI for chronic low back pain.',
        conclusion: 'L4-L5 disc herniation confirmed.',
        prescribingPhysician: 'Dr. Catherine Petit',
        assignedRadiologist: 'Fatima Benali',
        siteId: 'S003',
        siteName: 'CHU-Brest',
        sectorId: 'SEC010',
        sectorName: 'General',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E005-03',
        patientId: 'P005',
        patientName: 'Bastien Leroy',
        patientBirthDate: new Date('1992-09-17'),
        patientGender: 'M',
        title: 'X-Ray - Back',
        anatomicalRegion: 'Back',
        examDate: new Date('2024-11-25'),
        patientWeight: 77,
        patientAge: 32,
        diagnosis: 'negative',
        department: 'Rheumatology',
        description: 'Standard lumbar X-ray.',
        conclusion: 'Normal bone structures.',
        prescribingPhysician: 'Dr. Jean Dupont',
        assignedRadiologist: 'Thomas Dubois',
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC010',
        sectorName: 'General',
        status: 'completed',
        isUrgent: false
      },

      // Lucie Bernard - P006 (4 exams including cytology)
      {
        id: 'E006-01',
        patientId: 'P006',
        patientName: 'Lucie Bernard',
        patientBirthDate: new Date('2001-01-29'),
        patientGender: 'F',
        title: 'Cytology - Thyroid',
        anatomicalRegion: 'Neck',
        examDate: new Date('2025-01-06'),
        patientWeight: 58,
        patientAge: 24,
        diagnosis: 'pending',
        department: 'Endocrinology',
        description: 'Fine needle aspiration of thyroid.',
        conclusion: 'Analysis in progress, results pending validation.',
        prescribingPhysician: 'Dr. Marie Leclerc',
        assignedRadiologist: null,
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC002',
        sectorName: 'Cytology',
        status: 'in-progress',
        isUrgent: false
      },
      {
        id: 'E006-02',
        patientId: 'P006',
        patientName: 'Lucie Bernard',
        patientBirthDate: new Date('2001-01-29'),
        patientGender: 'F',
        title: 'Ultrasound - Thyroid',
        anatomicalRegion: 'Neck',
        examDate: new Date('2025-01-04'),
        patientWeight: 58,
        patientAge: 24,
        diagnosis: 'positive',
        department: 'Endocrinology',
        description: 'Thyroid ultrasound for palpable nodule.',
        conclusion: '15mm thyroid nodule detected.',
        prescribingPhysician: 'Dr. Pierre Martin',
        assignedRadiologist: 'Nicolas Martin',
        siteId: 'S002',
        siteName: 'CHU-Caen',
        sectorId: 'SEC008',
        sectorName: 'Throat',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E006-03',
        patientId: 'P006',
        patientName: 'Lucie Bernard',
        patientBirthDate: new Date('2001-01-29'),
        patientGender: 'F',
        title: 'CT Scan - Neck',
        anatomicalRegion: 'Neck',
        examDate: new Date('2024-12-18'),
        patientWeight: 57,
        patientAge: 23,
        diagnosis: 'negative',
        department: 'ENT',
        description: 'Cervical CT scan with injection.',
        conclusion: 'No significant lymphadenopathy.',
        prescribingPhysician: 'Dr. Sophie Durand',
        assignedRadiologist: 'Daniel Bernard',
        siteId: 'S002',
        siteName: 'CHU-Caen',
        sectorId: 'SEC008',
        sectorName: 'Throat',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E006-04',
        patientId: 'P006',
        patientName: 'Lucie Bernard',
        patientBirthDate: new Date('2001-01-29'),
        patientGender: 'F',
        title: 'Fluorescence - Thyroid',
        anatomicalRegion: 'Neck',
        examDate: new Date('2024-11-10'),
        patientWeight: 57,
        patientAge: 23,
        diagnosis: 'negative',
        department: 'Nuclear medicine',
        description: 'Technetium thyroid scintigraphy.',
        conclusion: 'Normal homogeneous uptake.',
        prescribingPhysician: 'Dr. Michel Bernard',
        assignedRadiologist: 'Damien Petit',
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC003',
        sectorName: 'Fluorescence',
        status: 'completed',
        isUrgent: false
      },

      // Sophie Girard - P007 (3 exams)
      {
        id: 'E007-01',
        patientId: 'P007',
        patientName: 'Sophie Girard',
        patientBirthDate: new Date('1978-12-03'),
        patientGender: 'F',
        title: 'MRI - Brain',
        anatomicalRegion: 'Head',
        examDate: new Date('2025-01-03'),
        patientWeight: 68,
        patientAge: 46,
        diagnosis: 'negative',
        department: 'Neurology',
        description: 'Brain MRI for persistent headaches.',
        conclusion: 'No structural abnormalities detected.',
        prescribingPhysician: 'Dr. Anne Rousseau',
        assignedRadiologist: 'Fatima Benali',
        siteId: 'S003',
        siteName: 'CHU-Brest',
        sectorId: 'SEC010',
        sectorName: 'General',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E007-02',
        patientId: 'P007',
        patientName: 'Sophie Girard',
        patientBirthDate: new Date('1978-12-03'),
        patientGender: 'F',
        title: 'CT Scan - Sinuses',
        anatomicalRegion: 'Head',
        examDate: new Date('2024-12-12'),
        patientWeight: 68,
        patientAge: 46,
        diagnosis: 'positive',
        department: 'ENT',
        description: 'Sinus CT scan for chronic sinusitis.',
        conclusion: 'Bilateral maxillary sinusitis confirmed.',
        prescribingPhysician: 'Dr. François Moreau',
        assignedRadiologist: 'Sylvie Moreau',
        siteId: 'S002',
        siteName: 'CHU-Caen',
        sectorId: 'SEC008',
        sectorName: 'Throat',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E007-03',
        patientId: 'P007',
        patientName: 'Sophie Girard',
        patientBirthDate: new Date('1978-12-03'),
        patientGender: 'F',
        title: 'X-Ray - Thorax',
        anatomicalRegion: 'Thorax',
        examDate: new Date('2024-10-20'),
        patientWeight: 67,
        patientAge: 45,
        diagnosis: 'negative',
        department: 'Internal medicine',
        description: 'Routine chest X-ray.',
        conclusion: 'Clear lung fields.',
        prescribingPhysician: 'Dr. Catherine Petit',
        assignedRadiologist: 'Claire Rousseau',
        siteId: 'S003',
        siteName: 'CHU-Brest',
        sectorId: 'SEC005',
        sectorName: 'Chest',
        status: 'completed',
        isUrgent: false
      },

      // Marc Lefebvre - P008 (2 exams)
      {
        id: 'E008-01',
        patientId: 'P008',
        patientName: 'Marc Lefebvre',
        patientBirthDate: new Date('1965-08-15'),
        patientGender: 'M',
        title: 'Colonoscopy - Colon',
        anatomicalRegion: 'Abdomen',
        examDate: new Date('2025-01-02'),
        patientWeight: 82,
        patientAge: 59,
        diagnosis: 'positive',
        department: 'Gastroenterology',
        description: 'Screening colonoscopy with biopsies.',
        conclusion: 'Adenomatous polyps detected and resected.',
        prescribingPhysician: 'Dr. Jean Dupont',
        assignedRadiologist: 'Damien Petit',
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC001',
        sectorName: 'Colon',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E008-02',
        patientId: 'P008',
        patientName: 'Marc Lefebvre',
        patientBirthDate: new Date('1965-08-15'),
        patientGender: 'M',
        title: 'CT Scan - Abdomen',
        anatomicalRegion: 'Abdomen',
        examDate: new Date('2024-11-28'),
        patientWeight: 81,
        patientAge: 59,
        diagnosis: 'negative',
        department: 'Gastroenterology',
        description: 'Abdominal CT scan for post-colonoscopy follow-up.',
        conclusion: 'No residual lesions detected.',
        prescribingPhysician: 'Dr. Marie Leclerc',
        assignedRadiologist: 'Thomas Dubois',
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC001',
        sectorName: 'Colon',
        status: 'completed',
        isUrgent: false
      },

      // Claire Fontaine - P009 (4 exams including cytology)
      {
        id: 'E009-01',
        patientId: 'P009',
        patientName: 'Claire Fontaine',
        patientBirthDate: new Date('1990-04-22'),
        patientGender: 'F',
        title: 'Cytology - Ascitic fluid',
        anatomicalRegion: 'Abdomen',
        examDate: new Date('2025-01-01'),
        patientWeight: 65,
        patientAge: 34,
        diagnosis: 'negative',
        department: 'Gastroenterology',
        description: 'Cytological analysis of ascitic fluid.',
        conclusion: 'No malignant cells, benign ascites.',
        prescribingPhysician: 'Dr. Pierre Martin',
        assignedRadiologist: 'Déborah Dupont',
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC002',
        sectorName: 'Cytology',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E009-02',
        patientId: 'P009',
        patientName: 'Claire Fontaine',
        patientBirthDate: new Date('1990-04-22'),
        patientGender: 'F',
        title: 'Ultrasound - Liver',
        anatomicalRegion: 'Abdomen',
        examDate: new Date('2024-12-25'),
        patientWeight: 65,
        patientAge: 34,
        diagnosis: 'pending',
        department: 'Hepatology',
        description: 'Liver ultrasound for assessment.',
        conclusion: 'Analysis in progress, results pending validation.',
        prescribingPhysician: 'Dr. Sophie Durand',
        assignedRadiologist: null,
        siteId: 'S001',
        siteName: 'CHU-Angers',
        sectorId: 'SEC010',
        sectorName: 'General',
        status: 'in-progress',
        isUrgent: false
      },
      {
        id: 'E009-03',
        patientId: 'P009',
        patientName: 'Claire Fontaine',
        patientBirthDate: new Date('1990-04-22'),
        patientGender: 'F',
        title: 'CT Scan - Abdomen',
        anatomicalRegion: 'Abdomen',
        examDate: new Date('2024-11-18'),
        patientWeight: 64,
        patientAge: 34,
        diagnosis: 'negative',
        department: 'Internal medicine',
        description: 'Abdominal CT scan with contrast.',
        conclusion: 'Normal abdominal organs.',
        prescribingPhysician: 'Dr. Michel Bernard',
        assignedRadiologist: 'Claire Rousseau',
        siteId: 'S003',
        siteName: 'CHU-Brest',
        sectorId: 'SEC010',
        sectorName: 'General',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E009-04',
        patientId: 'P009',
        patientName: 'Claire Fontaine',
        patientBirthDate: new Date('1990-04-22'),
        patientGender: 'F',
        title: 'Histology - Liver biopsy',
        anatomicalRegion: 'Abdomen',
        examDate: new Date('2024-10-15'),
        patientWeight: 64,
        patientAge: 34,
        diagnosis: 'negative',
        department: 'Pathology',
        description: 'Histological analysis of liver biopsy.',
        conclusion: 'Normal liver tissue, no fibrosis.',
        prescribingPhysician: 'Dr. Anne Rousseau',
        assignedRadiologist: 'Thomas Dubois',
        siteId: 'S003',
        siteName: 'CHU-Brest',
        sectorId: 'SEC007',
        sectorName: 'Histology',
        status: 'completed',
        isUrgent: false
      },

      // Antoine Roussel - P010 (3 exams)
      {
        id: 'E010-01',
        patientId: 'P010',
        patientName: 'Antoine Roussel',
        patientBirthDate: new Date('1982-11-08'),
        patientGender: 'M',
        title: 'CT Scan - Thorax',
        anatomicalRegion: 'Thorax',
        examDate: new Date('2024-12-31'),
        patientWeight: 85,
        patientAge: 42,
        diagnosis: 'pending',
        department: 'Pulmonology',
        description: 'Thoracic CT scan for persistent cough.',
        conclusion: 'Analysis in progress, results pending validation.',
        prescribingPhysician: 'Dr. François Moreau',
        assignedRadiologist: null,
        siteId: 'S003',
        siteName: 'CHU-Brest',
        sectorId: 'SEC004',
        sectorName: 'Lungs',
        status: 'scheduled',
        isUrgent: true
      },
      {
        id: 'E010-02',
        patientId: 'P010',
        patientName: 'Antoine Roussel',
        patientBirthDate: new Date('1982-11-08'),
        patientGender: 'M',
        title: 'X-Ray - Thorax',
        anatomicalRegion: 'Thorax',
        examDate: new Date('2024-12-10'),
        patientWeight: 85,
        patientAge: 42,
        diagnosis: 'negative',
        department: 'Internal medicine',
        description: 'Standard chest X-ray.',
        conclusion: 'Clear lung fields.',
        prescribingPhysician: 'Dr. Catherine Petit',
        assignedRadiologist: 'Julien Leroy',
        siteId: 'S003',
        siteName: 'CHU-Brest',
        sectorId: 'SEC005',
        sectorName: 'Chest',
        status: 'completed',
        isUrgent: false
      },
      {
        id: 'E010-03',
        patientId: 'P010',
        patientName: 'Antoine Roussel',
        patientBirthDate: new Date('1982-11-08'),
        patientGender: 'M',
        title: 'Bronchoscopy - Bronchi',
        anatomicalRegion: 'Thorax',
        examDate: new Date('2024-11-05'),
        patientWeight: 84,
        patientAge: 42,
        diagnosis: 'negative',
        department: 'Pulmonology',
        description: 'Bronchoscopy with bronchoalveolar lavage.',
        conclusion: 'No visible endobronchial lesions.',
        prescribingPhysician: 'Dr. Jean Dupont',
        assignedRadiologist: 'Claire Rousseau',
        siteId: 'S003',
        siteName: 'CHU-Brest',
        sectorId: 'SEC004',
        sectorName: 'Lungs',
        status: 'completed',
        isUrgent: false
      }
    ];
  }

  generateConversations(): Conversation[] {
    const conversations: Conversation[] = [];
    const users = this.generateUsers();
    const exams = this.generateExams().slice(0, 20);
    const currentUser = users[0]; // Damien
    
    const messageContents = [
      'Hello, I need your opinion on this case.',
      'The imaging results are quite interesting.',
      'Could you review the latest findings?',
      'I think we should discuss the treatment plan.',
      'The patient has been responding well.',
      'We might need additional tests.',
      'Please check the latest lab results.',
      'I recommend scheduling a follow-up.',
      'The diagnosis seems clear now.',
      'Let\'s coordinate the next steps.'
    ];
    
    exams.forEach((exam, index) => {
      const otherUser = users[(index % (users.length - 1)) + 1];
      const messageCount = 3 + (index % 4);
      const messages: Message[] = [];
      
      const isToday = index < 6;
      const baseDate = isToday ? new Date() : new Date(2024, 9 + (index % 3), 1 + (index % 28));
      
      for (let i = 0; i < messageCount; i++) {
        const messageDate = new Date(baseDate.getTime() + i * 30 * 60000);
        const isFromCurrentUser = i % 2 === 0;
        const sender = isFromCurrentUser ? currentUser : otherUser;
        
        messages.push({
          id: this.generateId(),
          senderId: sender.id,
          senderName: `${sender.firstName} ${sender.lastName}`,
          content: messageContents[i % messageContents.length],
          timestamp: messageDate,
          isRead: i < messageCount - 1 || index % 3 !== 0
        });
      }
      
      const isUnread = index < 3 || index === 4;
      const isPinned = index === 4 || index === 5;
      
      conversations.push({
        id: `C${String(index + 1).padStart(3, '0')}`,
        participants: [currentUser.id, otherUser.id],
        participantNames: [`${currentUser.firstName} ${currentUser.lastName}`, `${otherUser.firstName} ${otherUser.lastName}`],
        examId: exam.id,
        examTitle: exam.title,
        patientName: exam.patientName,
        lastMessage: messages[messages.length - 1],
        messages,
        isUnread,
        isPinned,
        createdAt: baseDate,
        updatedAt: messages[messages.length - 1].timestamp
      });
    });
    
    return conversations;
  }
}